### ISSUE TITLE
MCA Support Issue

### ISSUE THREAD

**Issue by ardissaps** [LIUKRAST/Skins3D#2]
[Minecraft Come Alive](https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn)
![image](https://user-images.githubusercontent.com/82106625/188291578-8714c475-87e1-4998-a16d-b6630e20aede.png)
![image](https://user-images.githubusercontent.com/82106625/188291586-f5806786-0d81-47d5-804c-36f90eacf13c.png)

**Comment by LIUKRAST** [comment]
Sorry for that huge late reply, i went completely offline from mc. Does the mod that you use override the vanilla Player Model?

**Comment by ardissaps** [comment]
> Sorry for that huge late reply, i went completely offline from mc. Does the mod that you use override the vanilla Player Model?

yes

**Comment by LIUKRAST** [comment]
Will be fixed in #3

**Comment by LIUKRAST** [comment]
Sorry #4 lol
