### ISSUE TITLE
[Optional] "blinking" feature 

### ISSUE THREAD

**Issue by leeineian** [LIUKRAST/Skins3D#5]
currently there's no in-game config to disable it.

**Comment by LIUKRAST** [comment]
Cause there's no need to disable it. Just do not put a blinking texture in your skin and it won't show up

**Comment by leeineian** [comment]
ah alright, thought the blinking feature had something to do with #3 that i still encounter in 1.20.4 (singleplayer & multiplayer)
![image](https://github.com/LIUKRAST/Skins3D/assets/86507806/3b1edab1-e37b-4471-b7c4-b0aef346cd40)
does this need investigating? ill check if its a conflict with a mod i have

**Comment by LIUKRAST** [comment]
Could you please tell me the other mods you're using? This may be an incompatibility

**Comment by leeineian** [comment]
ok as suspected it was the First Person Model mod by tr7zw that was conflicting with it - ive disabled it just now. the black square isnt frozen anymore, but now its sort of blinking.

**Comment by LIUKRAST** [comment]
So the black face is still blinking? _I'm assuming that you're using the latest (3.0.0) version of the mod_

**Comment by leeineian** [comment]
yup! latest version where you mentioned that it was already fixed in

**Comment by leeineian** [comment]
also now that we're here, in your free time maybe make the blinking interval customizable, just a suggestion.

**Comment by LIUKRAST** [comment]
I was actually thinking about making them random xD, but yeah, a config entry should do the trick
