### ISSUE TITLE
incompatibility with first person model mod 

### ISSUE THREAD

**Issue by rinkeChillow** [LIUKRAST/Skins3D#6]
when playing the model of the blinking eye somehow displays alongside the rest of the model resulting in an annoying flickering effect 
the effect is most noticeable when looking down 

![image](https://github.com/user-attachments/assets/556778e4-2424-45f0-88ff-4fd0769c4f25)

this one with just the eyes as the blink 
![image](https://github.com/user-attachments/assets/9d4f6024-d1c7-454f-8759-0d745ff912b8)

hope this get addressed soon.

**Comment by LIUKRAST** [comment]
Hello! Could you please specify the Loader, Minecraft version & first person model version?

**Comment by LIUKRAST** [comment]
Fixed in [3.0.1](https://github.com/LIUKRAST/Skins3D/commit/fbd0d480e260f4be484f8ad1184355aaadfe9c9e)

Available on Modrinth/Curseforge as soon as possible

**Comment by rinkeChillow** [comment]
keep the good work man
